Turning PDF and HTML content into Markdown
DL4DS/dl4ds_tutor pull request #22
Opened 2024-06-10 01:55 UTC by Farid-Karimli

- Added LlamaParser with GPT4o for parsing PDF documents into Markdown
- Added HTML into Markdown parsing

2024-06-10 12:32 UTC, XThomasBU commented
@Farid-Karimli Could you make this PR into the `dev_branch`

2024-06-12 16:03 UTC, trgardos requested changes
Needs to be able to pull content from the website without having to manually add files to the data directory.

2024-06-12 16:03 UTC, trgardos commented on code/config.yml
Try this with `expand_urls: True` to make sure it is loading and parsing the HTML and PDFs from the web site.

2024-06-12 16:04 UTC, trgardos commented on requirements.txt
I find it brittle to enumerate every package from pip freeze. I'll propose a small set of parent packages.

2024-06-12 16:06 UTC, trgardos commented
@Farid-Karimli -- did you merge updates from dev_branch into text_extract?

2024-06-12 16:10 UTC, XThomasBU commented on requirements.txt
I used pigar (https://github.com/damnever/pigar) to do this in the dev_branch (https://github.com/DL4DS/dl4ds_tutor/blob/dev_branch/requirements.txt)

2024-06-12 16:21 UTC, Farid-Karimli commented on requirements.txt
pigar gave me SEG faults

2024-06-12 17:05 UTC, Farid-Karimli commented
I didn't merge the updates from dev_branch into text_extraction

2024-06-20 21:00 UTC, Farid-Karimli commented
@XThomasBU @trgardos I refactored the code to parse PDF text and structure without GPT4o, so no image and not the best latex understanding. It also loads PDFs from their URLs temporarily onto the system for parsing.

2024-07-23 14:00 UTC, trgardos approved these changes

2024-07-23 16:08 UTC, merged